# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14Ny7PvRKzRl2rJAGpRMURCepp_aIwl1R
"""

import scipy.io.wavfile as wavfile
import matplotlib.pyplot as plt
import numpy as np
from IPython.display import Audio

"""## 2.1 Short-Time Energy"""

# Let’s load the speech signal first.
fs, s = wavfile.read('H.22.16k.wav')

frame1 = s[3600:4401]
N1 = len(frame1)
plt.figure()
plt.plot(np.arange(0, N1/fs, 1/fs), frame1)
plt.grid()
plt.title('A voiced frame')
plt.xlabel('time')


# Calculate maximum possible amplitude based on data type
max_amplitude = np.iinfo(s.dtype).max

# Normalize the frame and calculate energy
E1 = (1/N1)*sum((frame1.astype(np.float64) / max_amplitude)**2);
print(E1)

frame2 = s[4800:5001]
N2 = len(frame2)
plt.figure()
plt.plot(np.arange(0, N2/fs, 1/fs), frame2)
plt.grid()
plt.title('An unvoiced frame')
plt.xlabel('time')
# Listen
Audio(frame2, rate=fs)

# Calculate maximum possible amplitude based on data type
max_amplitude = np.iinfo(s.dtype).max

# Normalize the frame and calculate energy
E2 = (1/N2)*sum((frame2.astype(np.float64) / max_amplitude)**2);
print(E2)

plt.figure()
plt.stem(1, E1, linefmt=None, basefmt=None, label='Energy of Voiced frame')
plt.stem(2, E2, linefmt='red', basefmt=None, label='Energy of Unvoiced Frame')
plt.grid(True)
plt.xlim([0, 3])
plt.ylim([0, max(E1, E2)])
plt.title('Energy comparison')
plt.xlabel('Index')
plt.ylabel('Energy Value')
plt.show()

plt.figure()
plt.stem([1], [E1], linefmt='C0-', markerfmt='C0+', basefmt='k-', label='Zero Crossing Rate of Voiced frame')
plt.grid()
plt.stem([2], [E2], linefmt='C1-', markerfmt='C1x', basefmt='k-', label='Zero Crossing Rate of Unvoiced Frame');
plt.axis([0, 3, 0, max(E1,E2)])
plt.title('Zero Crossing Rate Comparison')
plt.xlabel('Index')
plt.ylabel('Zero Crossing Rate');
plt.legend();

"""## 2.2 Zero Crossings"""

plt.figure()
plt.subplot(2, 1, 1)
plt.plot(frame1)
plt.grid()
plt.title('Voiced frame')
plt.subplot(2, 1, 2)
plt.plot(frame2)
plt.grid()
plt.title('Unvoiced frame')
plt.xlabel('time')

ZCr1 = 0.5*sum(abs(np.sign(frame1[1:])-np.sign(frame1[:-1])))
ZCr2 = 0.5*sum(abs(np.sign(frame2[1:])-np.sign(frame2[:-1])))

plt.figure()
plt.stem([1], [ZCr1], linefmt='C0-', markerfmt='C0+', basefmt='k-', label='Zero Crossing Rate of Voiced frame')
plt.grid()
plt.stem([2], [ZCr2], linefmt='C1-', markerfmt='C1x', basefmt='k-', label='Zero Crossing Rate of Unvoiced Frame');
plt.axis([0, 3, 0, max(ZCr1,ZCr2)])
plt.title('Zero Crossing Rate Comparison')
plt.xlabel('Index')
plt.ylabel('Zero Crossing Rate');
plt.legend();

